runtime: nodejs18

env_variables:
  GEO_USERNAME: "sup3rmar1o"
  API_APPID : "SarangNi-project5-PRD-772bbdc3d-83209840"
  API_CERTID : "PRD-72bbdc3d1467-cff5-4bcb-8ceb-b910"
  GOOGLE_API_KEY : "AIzaSyBlxdHgSZeS2SS469TW1cNtol8kgMVjLTQ"
  GOOGLE_SEARCH_ENGINE_ID : "66560b60be4cb4248"
  DB_URL : "mongodb+srv://sarang:kJPsDclq0dJkSImZ@cluster0.anmb1ur.mongodb.net/?retryWrites=true&w=majority"